# https://projecteuler.net/problem=2

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

def solve():
  res = 0
  a = 1 # first num in Fibonacci Series
  b = 2 # second num in Fibanocci Series
  
  while a <= 4000000:
    if a % 2 == 0:
      res += a
    a, b = b, a+b
  return res

if __name__ == "__main__":
  print (solve())